export KYTHE_ROOT_DIRECTORY=$(dirname "$0")
export KYTHE_CORPUS="helloworld"
export KYTHE="/opt/kythe"
export KYTHE_OUTPUT_DIRECTORY="/tmp/kythe-output"
export KYTHE_OUTPUT_DIRECTORY_GS="$KYTHE_OUTPUT_DIRECTORY/gs"
export KYTHE_OUTPUT_DIRECTORY_SERVING="$KYTHE_OUTPUT_DIRECTORY/serving"

rm -rf "$KYTHE_OUTPUT_DIRECTORY"

mkdir -p "$KYTHE_OUTPUT_DIRECTORY"
mkdir -p "$KYTHE_OUTPUT_DIRECTORY_GS"
mkdir -p "$KYTHE_OUTPUT_DIRECTORY_SERVING"

$KYTHE_ROOT_DIRECTORY/extractor.sh
$KYTHE_ROOT_DIRECTORY/index.sh
$KYTHE_ROOT_DIRECTORY/server.sh